In [1]:
import pandas as pd

In [2]:
def main():
    dataset_df = pd.read_csv('../dataset.csv')
    dataset_df = dataset_df.drop(dataset_df.columns[0], axis=1)
    dataset_df.to_csv('dataset.csv', index=False)

    df = pd.read_csv('dataset.csv')
    display(df)

In [3]:
main()

,data,utente,passi,zscore_passi,bins_passi,bmi,zscore_bmi,bins_bmi
0,2016-04-01,d9874c86e6db7bf4c3959445b0b05a1bb8e60bbf,15346.64,0.785724,5.0,NaN,NaN,NaN
1,2016-04-02,d9874c86e6db7bf4c3959445b0b05a1bb8e60bbf,1632.27,-1.635985,1.0,NaN,NaN,NaN
2,2016-04-03,d9874c86e6db7bf4c3959445b0b05a1bb8e60bbf,5364.54,-0.976934,1.0,NaN,NaN,NaN
3,2016-04-04,d9874c86e6db7bf4c3959445b0b05a1bb8e60bbf,20001.99,1.607774,5.0,NaN,NaN,NaN
4,2016-04-05,d9874c86e6db7bf4c3959445b0b05a1bb8e60bbf,21179.90,1.815771,5.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
4239105,2017-03-27,a8c6c2b373f1929ff0a40f48a385d1594d62154a,5408.48,-0.442662,2.0,NaN,NaN,NaN
4239106,2017-03-28,a8c6c2b373f1929ff0a40f48a385d1594d62154a,5724.31,-0.356313,2.0,NaN,NaN,NaN
4239107,2017-03-29,a8c6c2b373f1929ff0a40f48a385d1594d62154a,8281.51,0.342835,4.0,NaN,NaN,NaN
4239108,2017-03-30,a8c6c2b373f1929ff0a40f48a385d1594d62154a,9439.98,0.659565,4.0,NaN,NaN,NaN
4239109,2017-03-31,a8c6c2b373f1929ff0a40f48a385d1594d62154a,5753.64,-0.348294,2.0,NaN,NaN,NaN